name:                comp-math-lab5
version:             0.1.0.0
github:              Deltaspace0/comp-math-lab5
license:             MIT
author:              Ruslan Gadeev
maintainer:          rgadeew@yandex.ru
copyright:           2023 Ruslan Gadeev

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Deltaspace0/comp-math-lab5#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- matrix
- monomer
- monomer-widgets
- text
- text-show
- vector

default-extensions:
- OverloadedStrings

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  comp-math-lab5-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - comp-math-lab5

tests:
  comp-math-lab5-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - comp-math-lab5
